CREATE TABLE users (
  _id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL,
  pwd VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE session_log (
  _id SERIAL PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users (_id),
  ssid VARCHAR(500) NOT NULL UNIQUE,
  isActive BOOLEAN, 
  created_time TIMESTAMPTZ NOT NULL DEFAULT NOW (),
  expiration_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 month',
  creation_ip CIDR
);

CREATE TABLE favorites (
  _id SERIAL PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users (_id),
  places_id VARCHAR(500) NOT NULL
);

CREATE TABLE comments (
  _id SERIAL PRIMARY KEY NOT NULL,
  user_id BIGINT REFERENCES users (_id),
  places_id BIGINT REFERENCES places (_id),
  content VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

